### ISSUE TITLE
SIGISVI Ciudades

### ISSUE THREAD

**Issue by Raffa444** [Raffa444/TODO_INFRA#22]

**Comment by yasabesquien** [comment]
ya está creada la base nueva con los datos que mandó Alvaro, falta aumentar el espacio en disco de la vm y hacer la copia de la carpeta con la app

**Comment by yasabesquien** [comment]
se avisó que hoy a las 16hs se apaga la vm para aumentarle disco

**Comment by yasabesquien** [comment]
se aumentó disco, se está configurando la url y la app

**Comment by yasabesquien** [comment]
Se le avisó a Nicolas Poneiman para que prueba la aplicación https://ciudades.seguridadvial.gob.ar

**Comment by yasabesquien** [comment]
Nicolas probá la nueva app y dice que tiene los mismos datos y usuarios que sigisvi, le mandé mail a Alvaro a ver que dice.

**Comment by yasabesquien** [comment]
Se entregaron ambos ambientes quedando https://sigisviciudades.seguridadvial.gob.ar y https://capacitacionsigisviciudades.seguridadvial.gob.ar con usuario admin
