### ISSUE TITLE
A/A  y  Alarmas DATACENTER

### ISSUE THREAD

**Issue by Raffa444** [Raffa444/TODO_INFRA#33]

**Comment by fheymannraggio** [comment]
Tenemos dos alertas, una por el filtro de cada aire acondicionado.
Llamé para levantar una solicitud y enviaron por mail el listado de los centros de servicio APC.

No puedo llamar por que estoy esperando que me den el número de contrato de mantenimiento.
El número de contrato se lo pedí por mail a Fernando Garay Barrera, de Schneider, ya que por teléfono fué imposible contactarlo.

Por otro lado, hice una prueba para que el sistema informe las alertas por mail y la prueba fué exitosa.
Sin embargo, hay demasiadas opciones para configurar, voy a solicitar la asistencia de un técnico, junto con la solución de los aires acondicionados.

**Comment by fheymannraggio** [comment]
![schneider](https://user-images.githubusercontent.com/20862423/33394870-7dee6e94-d522-11e7-86f2-04b0fa5e2572.jpg)

**Comment by fheymannraggio** [comment]
![imagen](https://user-images.githubusercontent.com/20862423/33395178-75777f8e-d523-11e7-9ecf-985767270277.png)

**Comment by fheymannraggio** [comment]
Atención al cliente me solicita una copia del contrato, siguen diciendo que lo tenemos vencidos.

Dice que mandemos la copia a "sol@schneider-electric.com"

Le solicité por mail la copia del contrato a Luciana Perez.

**Comment by fheymannraggio** [comment]
Contrato: 40001270
Vigencia: 20/03/2017 AL 20/03/2018

Equipamiento:
Symmetra PX2 | Symmetra PX 48 | PD1119360100
InRow | ACRP102 | UK1052311142
InRow | ACRP102 | UK1052311141

**Comment by fheymannraggio** [comment]
Mañana, el miércoles 20 de diciembre, van a venir los técnicos. 
Un aire quedó en Stand By por que empezó a tirar aire caliente y mucho ruido.

**Comment by fheymannraggio** [comment]
El técnico pasó ayer a hacer un diagnóstico, pero no solucionó el problema.

Llamé de nuevo a Schneider para que vuelva.

**Comment by fheymannraggio** [comment]
Números de teléfono y celulares, destinados a la atención de contratos de Schneider Electric Argentina.

Horario comercial (Lunes a Viernes de 8:30 a 17:30Hs)
Nivel Único: 4730-8811

Fuera de horario comercial
Primer Nivel:
Si Ud. tiene contrato 7x24 UPS APC 15 3196-0012
Si Ud. tiene contrato 7x24 UPS MGE 15 3196-0011
Si Ud. tiene contrato 7x24 AA Uniflair / APC 15 4074-4230
Si Ud. tiene contrato 7x24 Industrias 15 6877-0404
Si Ud. tiene contrato 7x24 Energy-Partner 15 6262-8383
Si Ud. tiene contrato 7x24 Building 15 3134-9313

Fuera de horario comercial
Segundo Nivel: 15 5369-0290 / 15 4565-8993

**Comment by fheymannraggio** [comment]
Hoy se le cargo gas al equipo que está más cerca del fondo, que tiene una pinchadura en el compresor y hay que buscarla en otra ocasión. También se le cargó aceite, dejandola en condiciones de operar.

No hay de momento stock de filtros, pero se acordó que se traerían a la brevedad.

**Comment by fheymannraggio** [comment]
Le mandé un mail a Adrian Tupone, de dinatech, con copia a Luciana Perez y Fernando Garay de schenider.

Le pregunté cuándo vienen con los filtros de aire.

**Comment by fheymannraggio** [comment]
Me llamó por teléfono Sebastian Jaime, Gerente de operaciones de Dinatech.
Tel: 6091-8863

Me dijo que se iba a encargar del caso, para solucionarlo lo antes posible.

**Comment by fheymannraggio** [comment]
Hoy vinieron a cambiar los filtros.

**Comment by fheymannraggio** [comment]
Hable por teléfono a Scheider para que nos ayuden a configurar las alertas, y para pedir el detalle de mantenimiento del año 2017.

**Comment by fheymannraggio** [comment]
Llamé por teléfono nuevamente, para que nos pasen el detalle de mantenimiento del 2017 y les pedimos también del 2016. También solicité nuevamente ayuda para configurar las alertas de la UPS.

**Comment by fheymannraggio** [comment]
Hoy mande mail a Luciana, y me llamaron por teléfono. Me dijeron que iban a preparar los detalles de mantenimiento en los siguientes días.

De las alertas me dijeron que ellos no se encargan del tema, que busque una guía en internet.

**Comment by fheymannraggio** [comment]
Contacto enviado por Adrian Tupone de Dinatech:

El contrato de APC es **40001270**, en el caso de que no les de respuesta pueden gestionar los incedentes con los equipos al **4730-8811**

-----------------------------------

Hablé con Hernan Nieves, el técnico, para que vengan a hacer una visita y resolver la pinchadura del Aire Acondicionado.

-----------------------------------

Llamé varias veces a Luciana, la coordinadora de Servicios, para que nos pase las llamadas que le hicimos en diciembre. Siempre me da el contestador. Por mail no me responde. Le dí el número de teléfono a Fernando García para que intente contactarla por la mañana.

**Comment by fheymannraggio** [comment]
hable con Pablo Lotartaro de Schneider, ya está pedido el técnico para mañana. 

Va a revisar el aire que tiene perdida en la condensadora.

Nro de ticket:   wo-05241416.

**Comment by fheymannraggio** [comment]
Vinieron a ver el aire, apróximandamente a las 15 hs, reafirmaron que tiene perdidas en la condensadora, y revisaron los niveles de presión del equipo con nro de serie uk1052311142. No se hizo ninguna reparación.

Le mandé un mail a pablo.lotartaro@schneider-electric.com <Pablo Lotartaro>, Gerente de Servicios, para que me diga cuándo vienen a reparar la perdida.

**Comment by fheymannraggio** [comment]
Pablo Lotartaro negó que hubiera una fuga, por que los técnicos informaron el 28 de marzo que las presiones eran normales. Acabo de enviarle fotos de la pérdida por mail, y una copia del informe del 26 de diciembre, para que no pueda negar el problema.

**Comment by fheymannraggio** [comment]
El AA empezó a tirar aire caliente a toda velocidad. Se le puso en StandBy.
Se le mandó un correo a Pablo Lotartaro informando la situación.

También llamé por teléfono recién a las 12:35 hs, para reportar el problema. 
Nro de ticket: AR40001270

**Comment by fheymannraggio** [comment]
El tecnico se presentó a cargar el refrigerante a las 17 hs.

**Comment by fheymannraggio** [comment]
Hoy 19/04/2018 se presentaron a reparar la pérdida en la condensadora.

El nuevo administrador de servicios es Hernan Impini
Tel         4730-8888 INT 307
Celular  11 5369 0290
Mail:     hernan.impini@schneider-electric.com

**Comment by fheymannraggio** [comment]
La fuga se detectó, se soldó, y se revisó los niveles de presión para verificar que no haya otra pérdida.
25/04/2018.
--------------------------------------------------------------
Las alarmas están configuradas y mandan alertas a infraestructura@seguridadvial.gob.ar
