### ISSUE TITLE
Resistencia CHaco

### ISSUE THREAD

**Issue by Raffa444** [Raffa444/TODO_INFRA#35]

**Comment by stevevojacek** [comment]
Programado para el 11 de diciembre al 13.

**Comment by fheymannraggio** [comment]
Aparte de la lentitud del sistema, me reportan de Chaco los siguientes errores recurrentes:

**Comment by fheymannraggio** [comment]
![error safit 1](https://user-images.githubusercontent.com/20862423/33619158-3845d058-d9c3-11e7-91b0-83e346934a76.jpeg)

**Comment by fheymannraggio** [comment]
![error safit 2](https://user-images.githubusercontent.com/20862423/33619177-42b3810c-d9c3-11e7-9fc5-cc56b3199373.jpeg)

**Comment by fheymannraggio** [comment]
El informe de Chaco fué terminado y entregado.
