### ISSUE TITLE
COMPRA Americantec

### ISSUE THREAD

**Issue by Raffa444** [Raffa444/TODO_INFRA#45]
gabriel costa gcosta@americantec.com.ar 5291-8989

1 . Disco rigido eva fc x 48
2. Cajon de discos hp eva sas  x 5
3. Cajon de discos hp eva fc x 4

**Comment by fgarcia76** [comment]
Contacto Gabriel Costa 5291-8989

04-01-2018 Se envia mail a   gcosta@americantec.com.ar
04-01 Nos comunicamos con Gabriel Costa, entre hoy y mañana nos va a informar la fecha de entrega.
05-01-18 Se envia nuevamente mail a Gabriel para pedirle fecha de entrega de los equipos.
05-01-18 Nos comunicamos con Gabriel Costa y la fecha tentativa de entrega seria la semana del 22-01
