### ISSUE TITLE
COMPRA Dinatech

### ISSUE THREAD

**Issue by Raffa444** [Raffa444/TODO_INFRA#47]
info@diantech.com.ar
6091-8880

Servidor tipo 1 x 4
Servidor Hp proliant Bl460c gen6 x 2

**Comment by fgarcia76** [comment]
Contacto Nicolas Rubio 6091-7704

04-01-2018 Se envia mail a   info@dinatech.com.ar
04/01 Hablamos con Mariela, nos comunica que Claudia Granero es quien lleva la O.C pero esta de vacaciones. Va a escalar a quien corresponda para que nos den una fecha de entrega.
05-01-18  se envia nuevamente mail  a Mariela para pedir fecha de entrega de los equipos
05-01 Hablamos por telefono con Nicolas Rubio y la fecha seria para el 25/01
