### ISSUE TITLE
COMPRA Nanotec

### ISSUE THREAD

**Issue by Raffa444** [Raffa444/TODO_INFRA#48]
4788-3174 info@nanotecsrl.com.ar

servidor tipo 2 x1
memoria servidor x32
disco rigido hp eva sas x 48

**Comment by fgarcia76** [comment]
Contacto Ignacio Casanova 4788-3174

03-01-2018 se envia mail a   info@nanotecsrl.com.ar
--
04-01-18 Nos comunicamos por telefono, en el dia de la fecha van a responder por mail la fecha de entrega.
05-01-2018 Se envia nuevamente mail   solicitando fecha de entrega

05-01-2018 Hablamos con Ignacio Casanova, nos informa que el servidor esta para la semana
que viene, pero los discos y memoria para dentro de 15 dias.
